### ISSUE TITLE
language-lua-0.8.0 does not compile with alex 3.1.5

### ISSUE THREAD

**Issue by peti** [osa1/language-lua#32]
Citing from http://hydra.cryp.to/build/1392402/nixlog/1/raw:

~~~~
src/Language/Lua/Annotated/Lexer.x:328:31:
    Not in scope: ‘ord’
    Perhaps you meant one of these:
      ‘ord#’ (imported from GHC.Exts), ‘or#’ (imported from GHC.Exts),
      ‘or’ (imported from Prelude)
~~~~~

**Comment by osa1** [comment]
Thanks for reporting. A new version is uploaded to Hackage.
